version: '3.5'
services:
  mysql:
    image: mariadb/server
    ports:
      - 3330:3306
    restart:
      unless-stopped
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=changeItToo
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=slim
      - MYSQL_USER=userslim
      - MYSQL_PASSWORD=Secr3t
    volumes:
      - ./schema/:/docker-entrypoint-initdb.d/
  php-fpm:
    #image: php:7-fpm
    image: edgd1er/slim4api-php
    build:
      context: Docker
      dockerfile: Dockerfile
    volumes:
      - .:/code
    depends_on:
      - mysql
  my_app:
    image: nginx:latest
    ports:
      - 0.0.0.0:8088:80
      - 0.0.0.0:8443:443
    environment:
      # set the parameter error_reporting=EALL
      PHP_INI_ERROR_REPORTING: E_ALL
      # Use the production php.ini file as a base
      #TEMPLATE_PHP_INI=production
    volumes:
      #- .:/usr/src/app/
      - .:/code
      - ./Docker/cert.pem:/etc/ssl/cert.pem
      - ./Docker/key.pem:/etc/ssl/key.pem
      - ./Docker/site.conf:/etc/nginx/conf.d/default.conf
    #      - ./Docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm